spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  freemarker:
    check-template-location: false


comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png

